Make geocoder and optional dependency
GreenBuildingRegistry/usaddress-scourgify pull request #35
Opened 2024-01-26 23:08 UTC by NickCrews

2026-06-30 21:53 UTC, wyardley commented
@fablet is this still maintained? Any chance this (or something like it) could get released?

2026-07-16 20:06 UTC, fablet requested changes

2026-07-16 20:06 UTC, fablet commented on scourgify/normalize.py
> +_GEOCODER_ERROR = (
Move this to the top under `# Constants`

2026-07-16 20:06 UTC, fablet commented on scourgify/normalize.py
> +def _geocode(s: str):
Move this to the top under `# Private Functions`
Fix Pep8 issues, ie: two empty lines between functions

2026-07-16 21:42 UTC, wyardley commented on scourgify/normalize.py
> +def _geocode(s: str):
If the author isn't still able or following this, could you make the little adjustments for them? Alternately, I'm happy to recreate this with the requested adjustments if it would be helpful.

2026-07-23 21:01 UTC, wyardley commented on scourgify/normalize.py
> +def _geocode(s: str):
@NickCrews are you still available to do the requested updates?

2026-07-25 01:40 UTC, NickCrews commented on scourgify/normalize.py
> +def _geocode(s: str):
I will apply these edits early next week. Thanks for the review!!

2026-07-28 05:39 UTC, NickCrews commented
Edits are in, let me know if that matched your intent @fablet @wyardley

2026-08-07 14:19 UTC, fablet approved these changes

2026-08-07 14:20 UTC, merged